/* Generated by Together */
package com.dimata.pos.entity.billing;

import com.dimata.qdep.entity.Entity;
import java.util.Date;
import java.util.Hashtable;

public class Billdetail extends Entity {

    private long billMainId = 0;
    private long unitId = 0;
    private long materialId = 0;
    private String itemName = "";
    private double itemPrice = 0.00;
    private int discType = 0;
    private double disc = 0.00;
    private double qty = 0;
    private double totalPrice = 0.00;
    private String sku = "";
    private int materialType = 0;
    private double cost = 0.00;
    private double discPct = 0.00;
    private Hashtable hashBilldetailCode = new Hashtable();
    private BillDetailCode billDetailCode = new BillDetailCode();
    private int updateStatus = 0;
    private double amountAvailForReturn = 0;
    private double qtyStock = 0;
    private double itemPriceStock = 0;
    private double discGlobal = 0;
    private double totalDisc = 0;
    private String note = "";
    private double disc1 = 0.00;
    private double disc2 = 0.00;
    private String noBill = "";
    private double totalTax = 0;
    private double totalSvc = 0;
    private long parentReturnId = 0;
    /**
     * UNTUK TOTAL AMOUNT ari_wiweka 20130701
     *
     * @return
     */
    private double totalAmount = 0.00;
    private double qtyIssue = 0.0;

    private double totalCost = 0.00;

    private String barcodeMat = "";

    //add opie untuk status order dan status print bill item
    private int status = 0;
    private int statusPrint = 0;

    private Date lengthOrder = new Date();
    private Date lengthFinishOrder = new Date();

    private int printStatus = 0;

    private long parentId = 0;
    private long cutomePackBillingId = 0;
    private long userOrderId = 0;
    private long userIdSentToChecker = 0;
    private Date dateSentToChecker = new Date();
    private Date dateUserToServed = new Date();
    private long userIdToServed = 0;
    private long costumeScheduleId = 0;

    //ARI ARDIADI
    private String unitName = "";

    //added by dewok 20190217
    private double guidePrice = 0;

    public long getBillMainId() {
        return billMainId;
    }

    public void setBillMainId(long billMainId) {
        this.billMainId = billMainId;
    }

    public long getUnitId() {
        return unitId;
    }

    public void setUnitId(long unitId) {
        this.unitId = unitId;
    }

    public long getMaterialId() {
        return materialId;
    }

    public void setMaterialId(long materialId) {
        this.materialId = materialId;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public double getItemPrice() {
        return itemPrice;
    }

    public void setItemPrice(double itemPrice) {
        this.itemPrice = itemPrice;
    }

    public int getDiscType() {
        return discType;
    }

    public void setDiscType(int discType) {
        this.discType = discType;
    }

    public double getDisc() {
        return disc;
    }

    public void setDisc(double disc) {
        this.disc = disc;
    }

    public double getQty() {
        return qty;
    }

    public void setQty(double qty) {
        this.qty = qty;
    }

    public double getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    public int getMaterialType() {
        return materialType;
    }

    public void setMaterialType(int materialType) {
        this.materialType = materialType;
    }

    public double getCost() {
        return cost;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    /**
     * Getter for property discPct.
     *
     * @return Value of property discPct.
     */
    public double getDiscPct() {
        return discPct;
    }

    /**
     * Setter for property discPct.
     *
     * @param discPct New value of property discPct.
     */
    public void setDiscPct(double discPct) {
        this.discPct = discPct;
    }

    /**
     * Getter for property billDetailCode.
     *
     * @return Value of property billDetailCode.
     */
    public com.dimata.pos.entity.billing.BillDetailCode getBillDetailCode() {
        return billDetailCode;
    }

    /**
     * Setter for property billDetailCode.
     *
     * @param billDetailCode New value of property billDetailCode.
     */
    public void setBillDetailCode(com.dimata.pos.entity.billing.BillDetailCode billDetailCode) {
        this.billDetailCode = billDetailCode;
    }

    /**
     * Getter for property hashBilldetailCode.
     *
     * @return Value of property hashBilldetailCode.
     */
    public Hashtable getHashBilldetailCode() {
        return hashBilldetailCode;
    }

    /**
     * Setter for property hashBilldetailCode.
     *
     * @param hashBilldetailCode New value of property hashBilldetailCode.
     */
    public void setHashBilldetailCode(Hashtable hashBilldetailCode) {
        this.hashBilldetailCode = hashBilldetailCode;
    }

    /**
     * Getter for property updateStatus.
     *
     * @return Value of property updateStatus.
     */
    public int getUpdateStatus() {
        return updateStatus;
    }

    /**
     * Setter for property updateStatus.
     *
     * @param updateStatus New value of property updateStatus.
     */
    public void setUpdateStatus(int updateStatus) {
        this.updateStatus = updateStatus;
    }

    /**
     * Getter for property amountAvailForReturn.
     *
     * @return Value of property amountAvailForReturn.
     */
    public double getAmountAvailForReturn() {
        return amountAvailForReturn;
    }

    /**
     * Setter for property amountAvailForReturn.
     *
     * @param amountAvailForReturn New value of property amountAvailForReturn.
     */
    public void setAmountAvailForReturn(double amountAvailForReturn) {
        this.amountAvailForReturn = amountAvailForReturn;
    }

    /**
     * Getter for property qtyStock.
     *
     * @return Value of property qtyStock.
     */
    public double getQtyStock() {
        return qtyStock;
    }

    /**
     * Setter for property qtyStock.
     *
     * @param qtyStock New value of property qtyStock.
     */
    public void setQtyStock(double qtyStock) {
        this.qtyStock = qtyStock;
    }

    public double getItemPriceStock() {
        return itemPriceStock;
    }

    public void setItemPriceStock(double itemPriceStock) {
        this.itemPriceStock = itemPriceStock;
    }

    /**
     * Getter for property discGlobal.
     *
     * @return Value of property discGlobal.
     */
    public double getDiscGlobal() {
        return discGlobal;
    }

    /**
     * Setter for property discGlobal.
     *
     * @param discGlobal New value of property discGlobal.
     */
    public void setDiscGlobal(double discGlobal) {

        this.discGlobal = discGlobal;
    }

    /**
     * @return the note
     */
    public String getNote() {
        return note;
    }

    /**
     * @param note the note to set
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * @return the disc1
     */
    public double getDisc1() {
        return disc1;
    }

    /**
     * @param disc1 the disc1 to set
     */
    public void setDisc1(double disc1) {
        this.disc1 = disc1;
    }

    /**
     * @return the disc2
     */
    public double getDisc2() {
        return disc2;
    }

    /**
     * @param disc2 the disc2 to set
     */
    public void setDisc2(double disc2) {
        this.disc2 = disc2;
    }

    /**
     * @return the totalAmount
     */
    public double getTotalAmount() {
        return totalAmount;
    }

    /**
     * @param totalAmount the totalAmount to set
     */
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * @return the totalDisc
     */
    public double getTotalDisc() {
        return totalDisc;
    }

    /**
     * @param totalDisc the totalDisc to set
     */
    public void setTotalDisc(double totalDisc) {
        this.totalDisc = totalDisc;
    }

    /**
     * @return the qtyIssue
     */
    public double getQtyIssue() {
        return qtyIssue;
    }

    /**
     * @param qtyIssue the qtyIssue to set
     */
    public void setQtyIssue(double qtyIssue) {
        this.qtyIssue = qtyIssue;
    }

    /**
     * @return the totalCost
     */
    public double getTotalCost() {
        return totalCost;
    }

    /**
     * @param totalCost the totalCost to set
     */
    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }

    /**
     * @return the barcodeMat
     */
    public String getBarcodeMat() {
        return barcodeMat;
    }

    /**
     * @param barcodeMat the barcodeMat to set
     */
    public void setBarcodeMat(String barcodeMat) {
        this.barcodeMat = barcodeMat;
    }

    /**
     * @return the status
     */
    public int getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * @return the statusPrint
     */
    public int getStatusPrint() {
        return statusPrint;
    }

    /**
     * @param statusPrint the statusPrint to set
     */
    public void setStatusPrint(int statusPrint) {
        this.statusPrint = statusPrint;
    }

    /**
     * @return the lengthOrder
     */
    public Date getLengthOrder() {
        return lengthOrder;
    }

    /**
     * @param lengthOrder the lengthOrder to set
     */
    public void setLengthOrder(Date lengthOrder) {
        this.lengthOrder = lengthOrder;
    }

    /**
     * @return the lengthFinishOrder
     */
    public Date getLengthFinishOrder() {
        return lengthFinishOrder;
    }

    /**
     * @param lengthFinishOrder the lengthFinishOrder to set
     */
    public void setLengthFinishOrder(Date lengthFinishOrder) {
        this.lengthFinishOrder = lengthFinishOrder;
    }

    /**
     * @return the noBill
     */
    public String getNoBill() {
        return noBill;
    }

    /**
     * @param noBill the noBill to set
     */
    public void setNoBill(String noBill) {
        this.noBill = noBill;
    }

    /**
     * @return the totalTax
     */
    public double getTotalTax() {
        return totalTax;
    }

    /**
     * @param totalTax the totalTax to set
     */
    public void setTotalTax(double totalTax) {
        this.totalTax = totalTax;
    }

    /**
     * @return the totalSvc
     */
    public double getTotalSvc() {
        return totalSvc;
    }

    /**
     * @param totalSvc the totalSvc to set
     */
    public void setTotalSvc(double totalSvc) {
        this.totalSvc = totalSvc;
    }

    /**
     * @return the printStatus
     */
    public int getPrintStatus() {
        return printStatus;
    }

    /**
     * @param printStatus the printStatus to set
     */
    public void setPrintStatus(int printStatus) {
        this.printStatus = printStatus;
    }

    /**
     * @return the parentId
     */
    public long getParentId() {
        return parentId;
    }

    /**
     * @param parentId the parentId to set
     */
    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    /**
     * @return the cutomePackBillingId
     */
    public long getCutomePackBillingId() {
        return cutomePackBillingId;
    }

    /**
     * @param cutomePackBillingId the cutomePackBillingId to set
     */
    public void setCutomePackBillingId(long cutomePackBillingId) {
        this.cutomePackBillingId = cutomePackBillingId;
    }

    /**
     * @return the parentReturnId
     */
    public long getParentReturnId() {
        return parentReturnId;
    }

    /**
     * @param parentReturnId the parentReturnId to set
     */
    public void setParentReturnId(long parentReturnId) {
        this.parentReturnId = parentReturnId;
    }

    /**
     * @return the userOrderId
     */
    public long getUserOrderId() {
        return userOrderId;
    }

    /**
     * @param userOrderId the userOrderId to set
     */
    public void setUserOrderId(long userOrderId) {
        this.userOrderId = userOrderId;
    }

    /**
     * @return the userIdSentToChecker
     */
    public long getUserIdSentToChecker() {
        return userIdSentToChecker;
    }

    /**
     * @param userIdSentToChecker the userIdSentToChecker to set
     */
    public void setUserIdSentToChecker(long userIdSentToChecker) {
        this.userIdSentToChecker = userIdSentToChecker;
    }

    /**
     * @return the dateSentToChecker
     */
    public Date getDateSentToChecker() {
        return dateSentToChecker;
    }

    /**
     * @param dateSentToChecker the dateSentToChecker to set
     */
    public void setDateSentToChecker(Date dateSentToChecker) {
        this.dateSentToChecker = dateSentToChecker;
    }

    /**
     * @return the dateUserToServed
     */
    public Date getDateUserToServed() {
        return dateUserToServed;
    }

    /**
     * @param dateUserToServed the dateUserToServed to set
     */
    public void setDateUserToServed(Date dateUserToServed) {
        this.dateUserToServed = dateUserToServed;
    }

    /**
     * @return the userIdToServed
     */
    public long getUserIdToServed() {
        return userIdToServed;
    }

    /**
     * @param userIdToServed the userIdToServed to set
     */
    public void setUserIdToServed(long userIdToServed) {
        this.userIdToServed = userIdToServed;
    }

    /**
     * @return the costunoeScheduleId
     */
    public long getCostumeScheduleId() {
        return costumeScheduleId;
    }

    /**
     * @param costunoeScheduleId the costunoeScheduleId to set
     */
    public void setCostumeScheduleId(long costunoeScheduleId) {
        this.costumeScheduleId = costunoeScheduleId;
    }

    /**
     * @return the unitName
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * @param unitName the unitName to set
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public double getGuidePrice() {
        return guidePrice;
    }

    public void setGuidePrice(double guidePrice) {
        this.guidePrice = guidePrice;
    }

}
