/* Generated by Together */



package com.dimata.hanoman.entity.system;



/* import java */

import java.util.*;



/* import java */

import com.dimata.hanoman.entity.system.*;



public class AppValue {

    

    public static final String SESS_APP_VALUE = "SESS_APP_VALUE";


    static boolean  sysPropLoaded=false;

    static Hashtable properties = new Hashtable();

    private static Hashtable feeManagementVilla = null;

    public static Hashtable getSystemProperties(){

        return properties;

    }



    public static void loadSystemProperty(){

        if (sysPropLoaded){
            return;
        }

        System.out.println(" ");

        System.out.println(" ");

        System.out.println("======-------------=====================");

        System.out.println("======-------------=====================");

        System.out.println("---LOADING SYSTEM PROPERTY INTO JSP SESSION");

        System.out.println(" ");

        System.out.println(" ");

        

        properties = new Hashtable();

        Vector listAll = PstSystemProperty.list(0,0, "", "");

        if(listAll!=null && listAll.size()>0){

            for(int i=0; i<listAll.size(); i++){

                SystemProperty sysprop = (SystemProperty)listAll.get(i);

                properties.put(""+sysprop.getName(), ""+sysprop.getValue());

            }

        }
        sysPropLoaded=true;
        
    }



     public static void loadNewSystemProperty(){

        System.out.println("======-------------=====================");

        System.out.println("---LOADING SYSTEM PROPERTY INTO JSP SESSION");

        System.out.println(" ");

        properties = new Hashtable();

        Vector listAll = PstSystemProperty.list(0,0, "", "");

        if(listAll!=null && listAll.size()>0){

            for(int i=0; i<listAll.size(); i++){

                SystemProperty sysprop = (SystemProperty)listAll.get(i);

                properties.put(""+sysprop.getName(), ""+sysprop.getValue());

            }

        }
        sysPropLoaded=true;
        loadManagementFee();
    }

    

    

    public static String getValueByKey(String keys){
         if (!sysPropLoaded){
           loadSystemProperty();
         }

        String value = "";

        try{

            value = (String)properties.get(keys);

            System.out.println("=> GET SYSPROP: "+keys+", result : "+value);

        }

        catch(Exception e){

            value = "";            

        }

        

        if(value==null){

            value = "";

        }

        

        return value;

    }


    public static void loadManagementFee() {
        try {
           if(feeManagementVilla==null){
               feeManagementVilla = new Hashtable();
           }
           String feeManagementPersentase = PstSystemProperty.getValueByName("FEE_MANAGEMENT_VILLA_HOTEL");
           String feeMarketingPersentase = PstSystemProperty.getValueByName("FEE_MARKETING_MANAGEMENT_VILLA_HOTEL");
           double persentaseManagement =0.0;
           double persentaseMarketing =0.0;
           if(feeManagementPersentase==null || Integer.parseInt(feeManagementPersentase)==0) {
                 persentaseManagement=0.0;
                 feeManagementVilla.put("FEE_MANAGEMENT_VILLA_HOTEL", persentaseManagement);
           } else {
                  persentaseManagement =  (Double.parseDouble(feeManagementPersentase)/100);
                  feeManagementVilla.put("FEE_MANAGEMENT_VILLA_HOTEL", persentaseManagement);
           }

           if(feeMarketingPersentase==null || Integer.parseInt(feeMarketingPersentase)==0) {
                 persentaseMarketing=0.0;
                 feeManagementVilla.put("FEE_MARKETING_MANAGEMENT_VILLA_HOTEL", persentaseMarketing);
           } else {
                  persentaseMarketing =  (Double.parseDouble(feeMarketingPersentase)/100);
                  feeManagementVilla.put("FEE_MARKETING_MANAGEMENT_VILLA_HOTEL", persentaseMarketing);
           }
        } catch (Exception e) {
            System.out.println("Exc : " + e.toString());
        } finally {
            return ;
        }
    }

    public static double getManagementFee(String key) {

        double result = 0.0;
        try {
           if(feeManagementVilla==null){
            loadManagementFee();
           }
           Double feeVilla = (Double) feeManagementVilla.get(key);
           if(feeManagementVilla!=null){
             result = feeVilla.doubleValue();
           }
        } catch (Exception e) {
            System.out.println("Exc getFeeManagement : " + e.toString());
        } finally {
            return result;
        }
    }


}

